### ISSUE TITLE
[WEBSITE] How to create references to samples?

### ISSUE THREAD

**Issue by cwiechmann** [Axway/axway-open-docs#1374]
## Issue description

The following page https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_howto_guides/apigw_in_containers/index.html has links to some sample files that are not working anymore. 

Example:
```[`anm-dockerfile`](/samples/apimanagement/howto/docker/anm-dockerfile)```

I have compared how other pages are referencing sample content and found the following page:
https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cli_central/cli_publish/index.html

This page is using the following syntax:
`[apiendpoint.json](https://axway-open-docs.netlify.app/samples/central/apiendpoint.json)`

Is it really the idea to create links to samples that way? I mean with a fully qualified hostname? Or is it a bug in the generator?

## Problem location

https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_howto_guides/apigw_in_containers/index.html

**Comment by andreamussap** [comment]
@cwiechmann the projects were using fully qualified hostname (https://docs.axway.com/bundle/...) because the Zoomin portal wasn't parsing relative paths (/samples/apimanagement/howto/docker/anm-dockerfile).

This has been fixed, and all projects now should use relative paths. I believe that all references in the axway-open-docs project are fixed. If you find one that isn't, please let me know.

Amplify Central documentation was moved to its own project - 
https://github.com/Axway/amplify-central. So, if you still see the issue there, you should open an Issue to the relevant project.

Thank you!
