### ISSUE TITLE
[DOC] Update RN terminology (install service pack -> install update)

### ISSUE THREAD

**Issue by alexearnshaw** [Axway/axway-open-docs#336]
## Issue description

For 20200130 and subsequent releases these are updates to 7.7 not service packs, so the terminology should reflect this.

## Problem location

https://axway-open-docs.netlify.com/docs/apim_relnotes/

## Suggestions for a fix

In the instructions to install 7.7.20200130 I think we'd want to differentiate between this release and the service packs of old right? So do you agree with changing the terminology in the install instructions from "install a service pack" to "install an update"?
That means we'd have 3 clearly different terms:

- update - 7.7.20200130 and subsequent releases
- upgrade - full upgrade using sysupgrade e.g. from 762 to 77
- install/apply a service pack or patch

[Above was agreed with @GianSchoeman ]

**Comment by andreamussap** [comment]
Just double checking - Since this terminology update is just for the **Installation Instructions**, and APIP doesn't have this section because they follow the same steps for install (clean installation of the portal and upgrade in case the customer want to upgrade to any 7.7 API portal version) so this update doesn't impact APIP ??
